server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Astro generates static output, this helps routing back to index if needed
        try_files $uri $uri/ /index.html;
    }

    # Endpoint required by Nginx Prometheus Exporter to collect metrics
    location /stub_status {
        stub_status on;
        access_log off;
        allow all; # In a strict prod environment, allow only docker subnet
    }
}